# Generated by Django 3.1 on 2020-08-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountprofile', '0004_auto_20200810_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
