# Generated by Django 3.1 on 2020-08-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountprofile', '0007_auto_20200818_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referree',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
