# Generated by Django 3.1 on 2020-08-09 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(default='true.jpg', upload_to='user/')),
                ('bankname', models.CharField(default='', max_length=200)),
                ('bankacc', models.CharField(default='', max_length=100)),
                ('accountname', models.CharField(default='', max_length=100)),
                ('package', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='accountprofile.package')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
