# Generated by Django 3.1 on 2020-08-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
