# Generated by Django 3.1 on 2020-08-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0003_auto_20200809_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='package',
            field=models.CharField(choices=[('1', '5000'), ('2', '10000'), ('3', '15000'), ('4', '20000')], max_length=200),
        ),
    ]
