# Generated by Django 3.1 on 2020-08-09 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountprofile', '0002_auto_20200809_1729'),
        ('diamond', '0004_auto_20200809_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='package',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='accountprofile.package'),
        ),
    ]
