# Generated by Django 3.1 on 2020-08-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0005_auto_20200809_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default='code', max_length=6),
        ),
    ]
