# Generated by Django 3.1 on 2020-08-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0007_auto_20200811_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default='code', max_length=6),
        ),
    ]
