# Generated by Django 3.1 on 2020-08-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0008_auto_20200811_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='referral_code',
        ),
    ]
