# Generated by Django 3.1 on 2020-08-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0011_auto_20200811_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default='YCOZX', max_length=6),
        ),
    ]
