# Generated by Django 3.1 on 2020-08-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0012_auto_20200812_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default='OJLKT', max_length=6),
        ),
    ]
