# Generated by Django 3.0.5 on 2020-08-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0013_auto_20200812_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default='LO01A', max_length=6),
        ),
    ]
