# Generated by Django 3.1 on 2020-08-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0015_auto_20200813_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referree',
            field=models.CharField(default='1', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default='4QACA', max_length=6),
        ),
    ]
