# Generated by Django 3.1 on 2020-08-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0016_auto_20200813_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default='HH6XY', max_length=6),
        ),
    ]
