# Generated by Django 3.1 on 2020-08-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0017_auto_20200813_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default='UTOLO', max_length=6),
        ),
    ]
