# Generated by Django 3.1 on 2020-08-18 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountprofile', '0009_auto_20200818_1439'),
        ('diamond', '0019_auto_20200818_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referree',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='accountprofile.referral'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default='AAFOC', max_length=6),
        ),
    ]
