# Generated by Django 3.1 on 2020-08-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0020_auto_20200818_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default='T4PNK', max_length=6),
        ),
    ]
