# Generated by Django 4.1.6 on 2023-02-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond', '0022_auto_20230201_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default='KHSEM', max_length=6),
        ),
    ]
